version: '3.4'

services:
  backend:
    build:
      context: .
      target: base
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 9002:3000
    depends_on:
      - dbupdate
    environment:
      DATABASE_URL: postgres://postgres@dbupdate
    tty: true
    stdin_open: true
  db:
    image: postgres:11.1-alpine
  dbupdate:
    image: postgres:13.5-alpine
    