version: "3.4"

services:
  web-app:
    image: web-app-admin
    build:
      context: .
      target: base
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9001:3000
    environment:
      REACT_APP_BACKEND_API_BASE: http://localhost:9002
